### ISSUE TITLE
感谢分享，另外请问一下我的主板也是技嘉的：Z370 gaming3，能通用吗？

### ISSUE THREAD

**Issue by SherlockGougou** [shijianzhiwai/Hackintosh-Gigabyte-Z370-OC-EFI#1]
https://www.gigabyte.cn/Motherboard/Z370-AORUS-Gaming-3-rev-10#kf

**Comment by shijianzhiwai** [comment]
> https://www.gigabyte.cn/Motherboard/Z370-AORUS-Gaming-3-rev-10#kf

这个只能试一下了，看着差别不大

**Comment by SherlockGougou** [comment]
好的感谢，我空了试试。

**Comment by SherlockGougou** [comment]
我发现Audio文件夹文件特别多，如果用不到的话建议删除：
![image](https://user-images.githubusercontent.com/17920617/91415059-0c6ab880-e880-11ea-9465-1196bfe4c3ac.png)

**Comment by shijianzhiwai** [comment]
嗯，这个当时只是添加GUI，就把OC官方文档上的项目整个移动过来了，但是我并没有设置启动音，这些应该可以直接删除。

https://dortania.github.io/OpenCore-Post-Install/cosmetic/gui.html#setting-up-opencore-s-gui
